### ISSUE TITLE
[Error] Build Fail

### ISSUE THREAD

**Issue by DPr00f** [Top-Cat/SteamKit-Java#1]
Hi Thomas,
I was building your steamkit but i get an error on building, the symmetric test under crypto doesn't fails to assert.
Do you know why? Aren't you getting any error?

I tried many times, if i comment the test building is fine.

Thanks

**Comment by elipsitz** [comment]
I've had this issue too. Make sure you have the updated Java unlimited key size thing (due to us export laws), and just check "skip tests". Appears to work fine.

**Comment by Top-Cat** [comment]
The test is actually a pretty good test because it shows this up :P
As above, make sure you have the JCE policy files installed otherwise java can't handle keys of the required length.
