### ISSUE TITLE
[Help] InvalidAuthCode EResult

### ISSUE THREAD

**Issue by krisser143** [Top-Cat/SteamKit-Java#10]
Hello, while trying to login with my LogOnDetails with only the username and password set (authCode at default), i get the InvalidAuthCode EResult, and no e-mail with the authcode. As i have heard, it should send the authcode to my E-Mail when i connected with a blank authcode. Do i need to request an authcode, or what do i do? I also want to mention that i get a NullPointerException if i login with an authCode with a value of null!

Oh, and while I'm here, how do i get the jobID of the UpdateMachineAuthCallback for the MachineAuthDetails, so i can use it in sendMachineAuthResponse?

Thanks for your help ;)

**Comment by DPr00f** [comment]
Hi Krisser, yes it should send you a code to the email, but that part is taken care by steam. So you might have encountered a problem with steam being down or something. Maybe the servers you've connected to were under maintenance. Would it help you if I create a sample project answering the questions you've mentioned above? I can squeeze that into my hobbies today/tomorrow.

**Comment by krisser143** [comment]
@DPr00f 
Sure, thanks for taking time helping me with this :D. I have tested the program for many days without any luck. It will just throw an InvalidAuthCode EResult, as if it already has registered that Steam has send the authcode to me.

Thanks again :)

**Comment by krisser143** [comment]
@DPr00f 
Not to hurry or anything, but how far have you come with the sample project?

**Comment by DPr00f** [comment]
Hey man, just added it https://github.com/DPr00f/SteamLog-JAVA

Here's what happened after running it

  1 Insert username:
  2 HIDDEN
  3 Insert password:
  4 HIDDEN
  5 Connection Status OK
  6 Login Failure: AccountLogonDenied
  7 This account is protected by Steam Guard.  Enter the authentication code sen    t to the proper email.
  8 X6D7N
  9 Disconnected from Steam Network, attemping to reconnect
 10 Connection Status OK
 11 Writing sentry file...
 12 Logged in

**Comment by DPr00f** [comment]
Not sure if it matters, but I've used java version 1.7 to compile and to run

**Comment by krisser143** [comment]
@DPr00f 
I'm also compiling with Java 1.7, though i just run it directly through IntelliJ, don't know if that changes anything. If i compile it and export libraries etc, and then run it from a .bat file, the same thing happens.

So my code were actually set up exactly like yours (though i just use Files.realAllBytes to read the sentry file).
The only thing i noticed was that you changed sentryFileHash to null, which doesn't change anything at all when trying to connect and login.

I also want to mention, that both our programs gets disconnected when it's trying to connect, and therefor tries to reconnect, which i think is a timeout to the Steam servers. It can connect though, after some retries (random amount of retries), but it just tells me that i used an invalid authentication code, in both our programs. So it can't be my code it's wrong with. Oh, and do you use the pre-compiled library (https://github.com/Top-Cat/SteamKit-Java/downloads)? I used it because IntelliJ vomited all over the place with errors, when i imported the files to IntelliJ, through the maven pom file.

And also, as you live in England (Your GitHub profile at least says), it's very unlikely that the servers is only experiencing problems at me, since i live in Denmark, very close to England. Maybe you are connecting to the GB servers, and I'm connecting to the Swedish servers, I'm not sure.
I don't think it's my account there is anything wrong with, as all my other friends also gets this error when they use my program. And that's, i want to mention, on different computers, behind different routers, with internet from different ISPs.

Only possibility, would be if we are connecting to different servers, though I'm quite sure they should perform the same, and connect to the big Database and Main server in Holland, or where ever the Main Server and Database is. OR, that I'm using a bugged library, because i couldn't compile the sourcecode from GitHub.

As Valve don't check for BOTs, the only likely possibility would be that my library is a bit bugged, though it could be something mentioned above...

**Comment by krisser143** [comment]
Yay, i found the download link!
https://github.com/Top-Cat/SteamKit-Java/downloads

**Comment by krisser143** [comment]
Ok, i just saw that the download link, which i used, was from 2012, which was the beginning of the library. If you could help me compile the source code, so i can get the fresh library, i would be more than grateful! This may not fix the issue, but there had been a lot of important commits since 2012, which might be the reason all of this is broken :(

EDIT: It's project lombok making all these errors when compiling. I'm looking around to see if i can fix it :)

EDIT: I don't know why IntelliJ can't compile Lombok code, even though it's added as a dependency and all that. I also noticed that the other type of errors is from Protobuf, because it can't read the protobuf files.

**Comment by krisser143** [comment]
Ok, i compiled successfully, i just needed to change some settings and such.

Thanks for the help anyways, you are very kind!!!!!!
And thanks for the sample, I'm using it as reference :)

**Comment by DPr00f** [comment]
Missed this comments dude. Sorry, I didn't help when you asked.
I've updated all the libraries on my sample, that might be the reason why it's working.
Also I've experienced problems connecting to some servers. Which tells me that some might be broken.
I'll double check and update steamkit if needed.

**Comment by krisser143** [comment]
@DPr00f 
Well, your code should work, as the whole problem was me not using the newest SteamKit. I had troubles compiling the source code from GitHub (SteamKit), so i downloaded a precompiled jar from this link: https://github.com/Top-Cat/SteamKit-Java/downloads, but it was old, which probably was the reason it had trouble connecting and sending the auth code. That's why the fix for this issue, was for me to just compile the source code, instead of using an old jar. But anyways, now it rarely Disconnects or timeouts when i connect, and the Steam Guard section of my code works wonderfully, and the sentry part is working fantastic :)
