### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by JeromeHuang** [Top-Cat/SteamKit-Java#11]

**Comment by JeromeHuang** [comment]
hi，I import the SteamKit-java project. However, there're many errors. Like this problem as follows:
Builder cannot be resolved to a type    ClientMsgProtobuf.java  /steamkit/src/main/java/uk/co/thomasc/steamkit/base line 112    Java Problem

I use jdk1.7. It seems that these problems relates to the Proto-Buf. How can I fix the problem?
The project doesn't update for a long time. I wonder if the project can still work.

**Comment by Top-Cat** [comment]
import proto.jar

**Comment by JeromeHuang** [comment]
import proto.jar. Does that mean import the dependency?
             <dependency>
            <groupId>com.google.protobuf</groupId>
            <artifactId>protobuf-java</artifactId>
            <version>2.4.1</version>
        </dependency>

**Comment by Top-Cat** [comment]
https://github.com/Top-Cat/SteamKit-Java/tree/master/src/repo

**Comment by JeromeHuang** [comment]
The errors are gone. Thank you!

**Comment by JeromeHuang** [comment]
I import the proto.jar and lombo.jar. Howerver the errors are still existing.For example,
Accept cannot be resolved to a variable UdpConnection.java  /steamkit/src/main/java/uk/co/thomasc/steamkit/networking/steam3    line 521    Java Problem
Challenge cannot be resolved to a variable  UdpConnection.java  /steamkit/src/main/java/uk/co/thomasc/steamkit/networking/steam3    line 518    Java Problem

It seems that the errors are related to Udp. I don't modify any code. How can I fix the errors?
Thanks.

**Comment by Top-Cat** [comment]
https://github.com/Top-Cat/SteamKit-Java/blob/b0f18031c63d2ed6bf1f599fa01894357d1f1f29/src/main/java/uk/co/thomasc/steamkit/base/generated/steamlanguage/EUdpPacketType.java#L8

They're right there

**Comment by JeromeHuang** [comment]
I fix the problem. I should install lombok.jar into eclipse. 
Thanks!
