### ISSUE TITLE
[QUESTION] 'generated' subpackage .pcjava files?

### ISSUE THREAD

**Issue by ghost** [Top-Cat/SteamKit-Java#5]
Ello,

So I was looking through the code and noticed that the whole project seems to be riddled with red flags.  I looked into some of the files that were marked and found that they had trouble reaching the classes in the "generated" sub-package.  Looking deeper into it, I found that the files had the extension .pcjava, which I was unable to find any documentation of and have never heard of before.  I assumed that this was a translation error as whatever program that was used to translate it probably did not recognize .pc as a file and attempted to just add java to the extension.  Anyway, so I redid the extensions on said files and the red flags seem to have vanished.

Has anyone else ran into this and should I have left them as .pcjava or is it good that I got them changed over?  They don't seem to present any errors now.  I have committed the files to my local fork @ https://github.com/Kdog59/SteamKit-Java/tree/master/src/main/java/uk/co/thomasc/steamkit/base/generated in case you would like to check the files.

**Comment by Top-Cat** [comment]
This is by design.
They take hours for eclipse to compile, pre-compiled versions are provided in repo/proto.java
