### ISSUE TITLE
No CallbackManager

### ISSUE THREAD

**Issue by krisser143** [Top-Cat/SteamKit-Java#9]
Apparently there is not very much documentation about this library. So I'm on my own, finding out how to use this. I watched some videos where they use the C# SteamKit. My problem is right now, that there is no CallbackManager that i can use.
I know i shouldn't watch C# videos about this, since it's Java, but there is no tutorials or such. I don't know how to recieve the callbacks, as the waitForCallback function is not working (neither is the getCallback function).

How do i recieve callbacks? I haven't programmed in some time :disappointed:

**Comment by DPr00f** [comment]
It's been a while since I've touched java, but basically what I ended doing using this library

```
private class RunnableUpdate implements Runnable{
        private boolean stop = false;
        @Override
        public void run() {
            while(!stop){
                update();
            }
        }
        private void update(){
            while(!stop){
                try {
                  CallbackMsg msg = steamClient.getCallback(true);
                  if(msg == null){
                        try {
                            Thread.sleep(500);
                        } catch (InterruptedException ex) {
                        }
                        break;
                    }
                    callbacksHandler.handleSteamMessages(msg);
                } catch (Exception e) {
                }
            }

            if(currentTrade != null){
                try{
                    currentTrade.Poll();
                }catch(Exception e){
                    String error = "Error polling the trade: " + e.getClass();
                    for (StackTraceElement el : e.getStackTrace()) {
                        error += "\n" + el;
                    }
                    console.println(error, false, ConsoleColors.Red);
                }
            }
        }
        private void setRunFlag(){
            stop = false;
        }
        private void setStopFlag() {
            stop = true;
        }
    }
```

msg contains the message from steam

**Comment by DPr00f** [comment]
Also @Top-Cat has a repo showing on how to use this library
https://github.com/Top-Cat/ScrapBank.tf

**Comment by krisser143** [comment]
@Top-Cat Thanks!
I were also planning on doing like this, but i thought there must have been an easier way to do it, as in the C# library. But thanks anyways, and also thanks for mentioning the ScrapBank library, it's a big help!
